### ISSUE TITLE
Throwing a "formElement" is a required for "page-designer" field error with M2.1.7

### ISSUE THREAD

**Issue by Judder** [Magenerds/PageDesigner#22]
Caches cleared and can enable / disable to reproduce the following exception - any suggestions where to look?

Thanks!

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The configuration parameter "formElement" is a required for "page-designer" field.

Exception #0 (Magento\Framework\Exception\LocalizedException): The configuration parameter "formElement" is a required for "page-designer" field.
#0 /client.com/vendor/magento/framework/View/Layout/Generator/UiComponent.php(148): Magento\Ui\Component\Form\Field->prepare()
#1 /vendor/magento/framework/View/Layout/Generator/UiComponent.php(145): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form\Field))
#2 /vendor/magento/framework/View/Layout/Generator/UiComponent.php(145): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form\Fieldset))
#3 /vendor/magento/framework/View/Layout/Generator/UiComponent.php(126): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Form))
#4 /vendor/magento/framework/View/Layout/Generator/UiComponent.php(93): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'cms_block_form', Array, Object(Magento\Framework\View\Layout\Interceptor))
#5 /vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#6 /vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 /var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#8 /vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#9 /vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#10 /vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#11 /vendor/magento/framework/View/Layout.php(244): Magento\Framework\View\Layout\Builder->build()
#12 /vendor/magento/framework/View/Layout.php(859): Magento\Framework\View\Layout->build()
#13 /var/generation/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('menu')
#14 /vendor/magento/module-backend/Model/View/Result/Page.php(59): Magento\Framework\View\Layout\Interceptor->getBlock('menu')
#15 /var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Cms::cm...')
#16 /vendor/magento/module-cms/Controller/Adminhtml/Block.php(42): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu('Magento_Cms::cm...')
#17 /vendor/magento/module-cms/Controller/Adminhtml/Block/Edit.php(57): Magento\Cms\Controller\Adminhtml\Block->initPage(Object(Magento\Backend\Model\View\Result\Page\Interceptor))
#18 /var/generation/Magento/Cms/Controller/Adminhtml/Block/Edit/Interceptor.php(24): Magento\Cms\Controller\Adminhtml\Block\Edit->execute()
#19 /vendor/magento/framework/App/Action/Action.php(102): Magento\Cms\Controller\Adminhtml\Block\Edit\Interceptor->execute()
#20 /vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#21 /vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Cms\Controller\Adminhtml\Block\Edit\Interceptor->___callParent('dispatch', Array)
#23 /vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Adminhtml\Block\Edit\Interceptor), Array, 'adminAuthentica...')
#24 /vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Block\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Cms\\Con...', 'dispatch', Object(Magento\Cms\Controller\Adminhtml\Block\Edit\Interceptor), Array, 'adminMassaction...')
#27 /vendor/magento/module-backend/App/Action/Plugin/MassactionKey.php(33): Magento\Cms\Controller\Adminhtml\Block\Edit\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /vendor/magento/framework/Interception/Interceptor.php(142): Magento\Backend\App\Action\Plugin\MassactionKey->aroundDispatch(Object(Magento\Cms\Controller\Adminhtml\Block\Edit\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /var/generation/Magento/Cms/Controller/Adminhtml/Block/Edit/Interceptor.php(39): Magento\Cms\Controller\Adminhtml\Block\Edit\Interceptor->___callPlugins('dispatch', Array, Array)
#30 /vendor/magento/framework/App/FrontController.php(55): Magento\Cms\Controller\Adminhtml\Block\Edit\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#31 /vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#33 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#34 /vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#35 /vendor/magento/framework/Interception/Interceptor.php(142): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#36 /var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#37 /vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#39 /index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#40 {main}
```

**Comment by Migno** [comment]
Have the same error, currently running a 2.1.5 until our upgrade to 2.2.x is complete.
I was about to use the latest here available version
